server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pigsty?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  cache:
    type: redis
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 1123
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    timeout: 0
  mvc:
    view:
      prefix: /WEB-INF/views/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com._220a220e.pigsty.*.entity
password:
  algorithmName: MD5
  hashIterations: 2

