spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pigsty?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1123
  redis:
    host: localhost
    port: 6379
    password: 1123
logging:
  level:
    com:
      _220a220e:
        mapper: DEBUG